Add ability to use QEMU and virtiofsd from package
HCK-CI/AutoHCK-Installer pull request #33
Opened 2024-04-22 14:59 UTC by kostyanf14

2024-04-25 12:20 UTC, akihikodaki commented
Why not just always use the packaged QEMU and save the additional `PACKAGE` variable and existing ones?

2024-04-25 12:30 UTC, kostyanf14 commented
> Why not just always use the packaged QEMU and save the additional `PACKAGE` variable and existing ones?

It is better to have the ability to compile a specific version if it is needed. Maybe switch the default to PACKAGE but leave the ability to compile too.

2024-04-25 12:34 UTC, akihikodaki requested changes

2024-04-25 12:34 UTC, akihikodaki commented on qemu.sh
> +  [ -f "${QEMU_IMG_BIN}" ] || log_fatal "QEMU_IMG_BIN file '$QEMU_IMG_BIN' does not exist. Please configure QEMU manually."
Why not call `check_qemu` instead?

2025-01-30 10:03 UTC, akihikodaki approved these changes

2025-01-30 17:13 UTC, merged